#!/bin/bash

binPath=$1
binFile=$2
mountPoint=$3
options=$4

mountPath=""

# check OS type to decide the mount path
if [[ "$OSTYPE" == "darwin"* ]]; then
    mountPath="/Volumes/"$mountPoint
    options=$options" -X"   # exclude metadata on darwin based OS
else
    mountPath="/media/$USER/"$mountPoint
fi

# print search path when verbose is enabled
if [[ "$options" == "-v"* ]]; then echo "Searching for Maxim board in "$searchPath
fi

# Verify that Maxim board is valid before copying(loading) the binary file
if ([ $mountPoint == "BOOTLOADER" ] && [ -e $mountPath"/DETAILS.TXT" ] && [ -e $mountPath"/HELP_FAQ.HTM" ]) \
    || ([ $mountPoint == "DAPLINK" ] && [ -e $mountPath"/DETAILS.TXT" ] && [ -e $mountPath"/MBED.HTM" ]); then

    cp $options $binPath/$binFile $mountPath
	# verify if file has been copied
	if [ ! -e $mountPath/$binFile ]; then
		echo "Can't upload the file to USB drive."
		exit 1
	fi
else
    echo "Maxim board not found."
    exit 1
fi
