#!/bin/bash

binPath=$1
binFile=$2
options=$3

daplinkPath=""
searchPath=""

# check OS type to decide search path and exclude metadata on darwin based OS
if [[ "$OSTYPE" == "darwin"* ]]; then
	searchPath="/Volumes"
	options=$options" -X"
else
	searchPath="/media"
fi

# print search path when verbose is enabled
if [[ "$options" == "-v"* ]]; then echo "Searching for Maxim board in "$searchPath
fi

# find the DETAILS.TXT file, store the path. write error to null
daplinkPath="$(find $searchPath -name DETAILS.TXT -exec dirname {} \; 2>/dev/null )"

# additional check to ensure copying binary file to Maxim board
if [ -e $daplinkPath/MBED.HTM ] || [ -e $daplinkPath/HELP_FAQ.HTM ]; then
	cp $options $binPath/$binFile $daplinkPath

	# verify if the file has been copied
	if [ ! -e $daplinkPath/$binFile ]; then
		echo "Can't upload the file to USB drive."
		exit 1
	fi
else
	echo "Maxim board not found."
	exit 1
fi
